### ISSUE TITLE
"state" instead of isWhatever

### ISSUE THREAD

**Issue by ghoeffner** [KiboOst/php-sunPos#1]
Hey, 

first of all thanks for releasing this! I need to tag pictures depending on date/time on a given location and was looking for a library that can just tell me what the current sun status is. Your library comes closest to the functionality, but I need to switch through all isWhatever cases right now. Would be great to just have a field that contains "Day", "Morning", "Noon", "Afternoon" etc.

My quickfix was for now using 
```
function getDayState($suncalobj) {
   if($suncalobj->isDay) {
    return "day";
   } elseif($suncalobj->isMorning) {
    return "morning";
   } elseif($suncalobj->isNoon) {
    return "noon";
   } elseif($suncalobj->isAfternoon) {
    return "afternoon";
   } elseif($suncalobj->isEvening) {
    return "evening";
   } else {
    return "night";
   }
}
```

**Comment by KiboOst** [comment]
Hi,

Please check v1.2 and the doc.
Thanks for the suggestion
